[package]
name = "backend-database"
version = "0.1.0"
edition = "2024"


[dependencies]
chrono = { workspace = true }
serde = { workspace = true }
sqlx = { version = "0.8", features = [
    "runtime-tokio-rustls",
    "sqlite",
    "macros",
    "chrono",
] }
thiserror = { workspace = true }
