services:
  api:
    build:
      context: .
      dockerfile: backend.Dockerfile
    environment:
      - DB_PATH=/data/data.db
    volumes:
      - type: bind
        source: ./data.db
        target: /data/data.db
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: frontend.Dockerfile
      args:
        VITE_API_BASE_URL: /api
    ports:
      - "3000:80"
    depends_on:
      - api
    restart: unless-stopped
    environment:
      IN_DOCKER: "1"