"""Add match types to matches

Revision ID: 062865ebee50
Revises: 7fe7d4c72f32
Create Date: 2025-08-13 13:12:39.423896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '062865ebee50'
down_revision: Union[str, None] = '7fe7d4c72f32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('MENS', 'MIXED', 'IMBALANCED_MIXED', 'LADIES', 'UNDEFINED', name='type'), nullable=False))


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
