"""Create person to player association

Revision ID: 7fe7d4c72f32
Revises: cc7f25ef7cf0
Create Date: 2025-08-13 10:30:01.626079

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7fe7d4c72f32"
down_revision: Union[str, None] = "cc7f25ef7cf0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "person",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
    )
    with op.batch_alter_table("player", schema=None) as batch_op:
        batch_op.add_column(sa.Column("person_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key("person_id_fkey", "person", ["person_id"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player", schema=None) as batch_op:
        batch_op.drop_constraint("person_id_fkey", type_="foreignkey")
        batch_op.drop_column("person_id")
    op.drop_table("person")

    # ### end Alembic commands ###
