"""Add constraint to session for uniqueness

Revision ID: cc7f25ef7cf0
Revises: 86f5eacd4891
Create Date: 2025-08-13 08:17:31.346522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc7f25ef7cf0'
down_revision: Union[str, None] = '86f5eacd4891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_club_session', ['date', 'club_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_constraint('unique_club_session', type_='unique')

    # ### end Alembic commands ###
